using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;


public class UIController : MonoBehaviour
{
    public static UIController instance;

    public Slider healthSlider;
    public Text healthText;

    public GameObject deathScreen;
    public string newGameScene, mainMenuScene;


    private void Awake()
    {
        instance = this;
    }

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void NewGameScene()
    {
        SceneManager.LoadScene(newGameScene);
    }
    public void MainMenuScene()
    {
        SceneManager.LoadScene(mainMenuScene);
    }
}
